### ISSUE TITLE
Careful when using of ngx.var.* and ngx.ctx.*

### ISSUE THREAD

**Issue by ddragosd** [openwhisk/openwhisk-apigateway#121]
`ngx.var.*` has a slight impact on performance as lua needs to go out of its VM into NGINX's memory, perform a lookup to read the variable, and then come back. The same thing happens with `ngx.ctx.*`

From the [docs](https://github.com/openresty/lua-nginx-module#ngxctx) on `ngx.ctx`
> The ngx.ctx lookup requires relatively expensive metamethod calls and it is much slower than explicitly passing per-request data along by your own function arguments. So do not abuse this API for saving your own function arguments because it usually has quite some performance impact.

An example from the current code base:
```lua
  local resourceKeys = redis.getAllResourceKeys(red, ngx.var.tenant)
  local redisKey = _M.findRedisKey(resourceKeys, ngx.var.tenant, ngx.var.gatewayPath)
```

Let's improve the example:
```lua
local tenant = ngx.var.tenant
local gatewayPath = ngx.var.gatewayPath
local resourceKeys = redis.getAllResourceKeys(red, tenant)
local redisKey = _M.findRedisKey(resourceKeys, tenant, gatewayPath)
```
This time the code performed a single read from NGINX using `ngx.var`, then it stored the value into a local lua variable to be reused.

**Comment by alexsong93** [comment]
Thanks! This issue has now been addressed for the example provided (see [here](https://github.com/openwhisk/openwhisk-apigateway/blob/master/scripts/lua/routing.lua#L46)), and for other places where `ngx.var.*` is used.
