### ISSUE TITLE
Integrate against OpenWhisk

### ISSUE THREAD

**Issue by markusthoemmes** [openwhisk/openwhisk-apigateway#134]
A recent change broke the entire OpenWhisk pipeline because this repository is not integrated against OpenWhisk and the routemanagement package.

A proposal would be:

1. Stand up an OpenWhisk deployment
2. Install the routemanagement package
3. Run tests against the routemanagement package

That would also clean up entanglement of API GW and OpenWhisk concerns as the package would move into this repository ideally.

Adding @mdeuser and @csantanapr.

**Comment by rabbah** [comment]
Cross-linking openwhisk issue https://github.com/openwhisk/openwhisk/issues/1955.

**Comment by rabbah** [comment]
Perhaps the routemgmt integration needs to move here then this can operate completely independently.

**Comment by csantanapr** [comment]
Now this is really solved in Travis https://github.com/openwhisk/openwhisk-apigateway/pull/143
but it remains the move of the apigateway cli plugin to this repo
