### ISSUE TITLE
GET of API with enabled CORS returns 'null' instead of 'true'

### ISSUE THREAD

**Issue by mdeuser** [openwhisk/openwhisk-apigateway#186]
1. Use the API GW management I/F to create (POST) an API with CORS enabled
2. Observe the following CORS setting in the POST response
```
     cors:
         enabled: true
```
3. GET the same API via API GW management IF (GET on the /api/SPACEGUID/BASEPATH endpoint)
4. The returned JSON has
```
...
"cors": {
    "enabled": null
}
...
```

Also, when an API is created via the CLI and CORS is not enabled, the returned API from GET does not have the CORS field at all.

**Comment by codymwalker** [comment]
https://github.ibm.com/bluemix-native-apim/bridge-whisk/blob/develop/utils/utils.js#L66

Looks like we are explicitly stripping out the configuration details here.

**Comment by mhamann** [comment]
This is an internal issue. Please open it accordingly.

**Comment by csantanapr** [comment]
@mhamann this doesn't have to do anything with UI.

We want to configure cors, we send cors configuration to the REST Management API, then when we retrieve the configuration comes back as nulll.

Are we using the wrong cors syntax in the swagger file when we use the REST API?

More details would help understand better the problem, and how are we suppose to configure/enable cors.

**Comment by csantanapr** [comment]
Also notice that the WSK CLI is only one, we use the `wsk api` command to configure the API Gateway in open source deployments.

**Comment by csantanapr** [comment]
To clarify the CLI is being used against the management API on the open source apigateway container running on local ubuntu, when the confit is retrieve from this API gateway the value for cors is null

**Comment by mhamann** [comment]
@alexsong93 ^
