### ISSUE TITLE
Figure out how to seperate database into it's own module

### ISSUE THREAD

**Issue by taylorking** [openwhisk/openwhisk-apigateway#77]
RIght now, the API resources, subscriptions, rate limiting, etc are tightly coupled to redis. While redis is probably one of the better technologies for these pieces, it may be desirable to plug in other storage solutions in the future.

In this case, we should pull all of the redis-specific logic into its own layer, such that someone could write a different "plugin" that matches the API and then use whatever backend they'd like.

**Comment by alexsong93** [comment]
A related Issue for implementing a DAO adapter layer has been opened here: https://github.com/openwhisk/openwhisk-apigateway/issues/183
